/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.tony.events;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TaskStarted extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1792335799667702162L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TaskStarted\",\"namespace\":\"com.linkedin.tony.events\",\"fields\":[{\"name\":\"taskType\",\"type\":\"string\"},{\"name\":\"taskIndex\",\"type\":\"int\"},{\"name\":\"host\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TaskStarted> ENCODER =
      new BinaryMessageEncoder<TaskStarted>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TaskStarted> DECODER =
      new BinaryMessageDecoder<TaskStarted>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TaskStarted> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TaskStarted> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TaskStarted>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TaskStarted to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TaskStarted from a ByteBuffer. */
  public static TaskStarted fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence taskType;
  @Deprecated public int taskIndex;
  @Deprecated public java.lang.CharSequence host;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TaskStarted() {}

  /**
   * All-args constructor.
   * @param taskType The new value for taskType
   * @param taskIndex The new value for taskIndex
   * @param host The new value for host
   */
  public TaskStarted(java.lang.CharSequence taskType, java.lang.Integer taskIndex, java.lang.CharSequence host) {
    this.taskType = taskType;
    this.taskIndex = taskIndex;
    this.host = host;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return taskType;
    case 1: return taskIndex;
    case 2: return host;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: taskType = (java.lang.CharSequence)value$; break;
    case 1: taskIndex = (java.lang.Integer)value$; break;
    case 2: host = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'taskType' field.
   * @return The value of the 'taskType' field.
   */
  public java.lang.CharSequence getTaskType() {
    return taskType;
  }

  /**
   * Sets the value of the 'taskType' field.
   * @param value the value to set.
   */
  public void setTaskType(java.lang.CharSequence value) {
    this.taskType = value;
  }

  /**
   * Gets the value of the 'taskIndex' field.
   * @return The value of the 'taskIndex' field.
   */
  public java.lang.Integer getTaskIndex() {
    return taskIndex;
  }

  /**
   * Sets the value of the 'taskIndex' field.
   * @param value the value to set.
   */
  public void setTaskIndex(java.lang.Integer value) {
    this.taskIndex = value;
  }

  /**
   * Gets the value of the 'host' field.
   * @return The value of the 'host' field.
   */
  public java.lang.CharSequence getHost() {
    return host;
  }

  /**
   * Sets the value of the 'host' field.
   * @param value the value to set.
   */
  public void setHost(java.lang.CharSequence value) {
    this.host = value;
  }

  /**
   * Creates a new TaskStarted RecordBuilder.
   * @return A new TaskStarted RecordBuilder
   */
  public static com.linkedin.tony.events.TaskStarted.Builder newBuilder() {
    return new com.linkedin.tony.events.TaskStarted.Builder();
  }

  /**
   * Creates a new TaskStarted RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TaskStarted RecordBuilder
   */
  public static com.linkedin.tony.events.TaskStarted.Builder newBuilder(com.linkedin.tony.events.TaskStarted.Builder other) {
    return new com.linkedin.tony.events.TaskStarted.Builder(other);
  }

  /**
   * Creates a new TaskStarted RecordBuilder by copying an existing TaskStarted instance.
   * @param other The existing instance to copy.
   * @return A new TaskStarted RecordBuilder
   */
  public static com.linkedin.tony.events.TaskStarted.Builder newBuilder(com.linkedin.tony.events.TaskStarted other) {
    return new com.linkedin.tony.events.TaskStarted.Builder(other);
  }

  /**
   * RecordBuilder for TaskStarted instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TaskStarted>
    implements org.apache.avro.data.RecordBuilder<TaskStarted> {

    private java.lang.CharSequence taskType;
    private int taskIndex;
    private java.lang.CharSequence host;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.linkedin.tony.events.TaskStarted.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.taskType)) {
        this.taskType = data().deepCopy(fields()[0].schema(), other.taskType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskIndex)) {
        this.taskIndex = data().deepCopy(fields()[1].schema(), other.taskIndex);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.host)) {
        this.host = data().deepCopy(fields()[2].schema(), other.host);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TaskStarted instance
     * @param other The existing instance to copy.
     */
    private Builder(com.linkedin.tony.events.TaskStarted other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.taskType)) {
        this.taskType = data().deepCopy(fields()[0].schema(), other.taskType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.taskIndex)) {
        this.taskIndex = data().deepCopy(fields()[1].schema(), other.taskIndex);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.host)) {
        this.host = data().deepCopy(fields()[2].schema(), other.host);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'taskType' field.
      * @return The value.
      */
    public java.lang.CharSequence getTaskType() {
      return taskType;
    }

    /**
      * Sets the value of the 'taskType' field.
      * @param value The value of 'taskType'.
      * @return This builder.
      */
    public com.linkedin.tony.events.TaskStarted.Builder setTaskType(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.taskType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'taskType' field has been set.
      * @return True if the 'taskType' field has been set, false otherwise.
      */
    public boolean hasTaskType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'taskType' field.
      * @return This builder.
      */
    public com.linkedin.tony.events.TaskStarted.Builder clearTaskType() {
      taskType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'taskIndex' field.
      * @return The value.
      */
    public java.lang.Integer getTaskIndex() {
      return taskIndex;
    }

    /**
      * Sets the value of the 'taskIndex' field.
      * @param value The value of 'taskIndex'.
      * @return This builder.
      */
    public com.linkedin.tony.events.TaskStarted.Builder setTaskIndex(int value) {
      validate(fields()[1], value);
      this.taskIndex = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'taskIndex' field has been set.
      * @return True if the 'taskIndex' field has been set, false otherwise.
      */
    public boolean hasTaskIndex() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'taskIndex' field.
      * @return This builder.
      */
    public com.linkedin.tony.events.TaskStarted.Builder clearTaskIndex() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'host' field.
      * @return The value.
      */
    public java.lang.CharSequence getHost() {
      return host;
    }

    /**
      * Sets the value of the 'host' field.
      * @param value The value of 'host'.
      * @return This builder.
      */
    public com.linkedin.tony.events.TaskStarted.Builder setHost(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.host = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'host' field has been set.
      * @return True if the 'host' field has been set, false otherwise.
      */
    public boolean hasHost() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'host' field.
      * @return This builder.
      */
    public com.linkedin.tony.events.TaskStarted.Builder clearHost() {
      host = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TaskStarted build() {
      try {
        TaskStarted record = new TaskStarted();
        record.taskType = fieldSetFlags()[0] ? this.taskType : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.taskIndex = fieldSetFlags()[1] ? this.taskIndex : (java.lang.Integer) defaultValue(fields()[1]);
        record.host = fieldSetFlags()[2] ? this.host : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TaskStarted>
    WRITER$ = (org.apache.avro.io.DatumWriter<TaskStarted>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TaskStarted>
    READER$ = (org.apache.avro.io.DatumReader<TaskStarted>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
